apiVersion: v1
kind: Service
metadata:
  name: aioquic
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: websecure-udp
      targetPort: 4433
      nodePort: 30433
      port: 4433
  selector:
    app: aioquic
